name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@modelstation.online << 'EOF'
            set -e

            cd /var/www/html/pallavin-be

            # pull latest changes
            git pull

            # install dependencies
            npm install

            # check if pm2 process exists
            if pm2 describe api-pallavin > /dev/null 2>&1; then
              echo "PM2 process exists. Restarting..."
              pm2 restart api-pallavin
            else
              echo "PM2 process not found. Starting new process..."
              pm2 start npm --name api-pallavin -- start
            fi

            # save pm2 state (so it restarts on reboot)
            pm2 save
          EOF
